# Generated by Django 5.0.3 on 2024-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
